
name: Azure Lab
run-name: Lab Practice

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: Access Token
        required: true
      account_id:
        type: string
        description: Account ID
        required: true
      location:
        type: choice
        description: 'Location'
        required: false
        options:
          - 'default'
          - 'westus2'
          - 'southcentralus'
          - 'centralus'
          - 'eastus'
          - 'westeurope'
          - 'southeastasia'
          - 'japaneast'
          - 'brazilsouth'
          - 'australiasoutheast'
          - 'centralindia'

jobs:

  Create-an-Azure-Resource-using-scripts:
    runs-on: windows-2022
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    environment: AzureLab

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Prepare
        shell: powershell
        run: |
          [System.String[]]$packages = @(
            ##'Az.Accounts',
            'Az.Resources',
            'Az'
          );
          [System.String[]]$skip = @(
            'Az'
          );
          ## https://www.powershellgallery.com/packages/Az/
          foreach ($azp in $packages)
          {
            if ( ${skip}.Contains("${azp}") ) {
              continue;
            }
            Install-Module -Name "${azp}" -Scope CurrentUser -Repository PSGallery -AllowClobber -Force;
          }
          foreach ($azp in $packages)
          {
            if ( ${skip}.Contains("${azp}") ) {
              continue;
            }
            Get-InstalledModule -Name "${azp}";
          }
          

      - name: Connect
        env:
          TOKEN : "${{ github.event.inputs.token }}"
          ID    : "${{ github.event.inputs.account_id }}"
        shell: powershell
        run: |
          [System.String]$Token = "${Env:TOKEN}";
          [System.String]$Id    = "${Env:ID}";
          [Microsoft.Azure.Commands.Profile.Models.Core.PSAzureProfile]$Profile=(Connect-AzAccount -AccessToken "${Token}" -AccountId "${Id}");
          Write-Output ${Profile};
          [System.String]$Expire = (Get-AzAccessToken).ExpiresOn.ToString('u');
          Write-Output "The session will expire at ${Expire}. "
          [Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription[]]$Subscriptions = (Get-AzSubscription);
          Write-Output ${Subscriptions};
          if ( ${Subscriptions}.Count -eq 0 ) {
            Write-Error -Message 'There is no subscription. '
            exit 1;
          }

      - name: Get Resource Group Information and Determine Location
        env:
          LOCATION : "${{ github.event.inputs.location }}"
        shell: powershell
        run: |
          [Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceProviderLocation[]] $Locations     = (Get-AzLocation);
          [System.Collections.Specialized.OrderedDictionary]                                        $Location_Dict = [ordered]@{};
          ${Locations} |
            Where-Object -FilterScript { $_.RegionType -eq 'Physical' } |
            ForEach-Object -Process {
              [System.String]$Location         = $_.Location;
              [System.String]$DisplayName      = $_.DisplayName;
              [System.String]$PhysicalLocation = $_.PhysicalLocation;
              [System.String]$GeographyGroup   = $_.GeographyGroup;
              [System.String]$DisplayLocation  = "${PhysicalLocation}, ${GeographyGroup}";
              if ( "${PhysicalLocation}" -eq '') {
                [System.String]$DisplayLocation = "${GeographyGroup}";
              }
              $Location_Dict["${Location}"]    = "${DisplayName} (${Location}), ${DisplayLocation}";
            }
          
          [Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceGroup[]]$ResourceGroups = (Get-AzResourceGroup);
          Write-Output ${ResourceGroups}
          if ( ${ResourceGroups}.Count -gt 0 ) {
            [Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceGroup]$group = ${ResourceGroups}[0];
            [System.String]$groupname      = $group.ResourceGroupName;
            [System.String]$glocation      = $group.Location;
            [System.String]$location_disp  = "${glocation}";
            if ( $Location_Dict.Contains("${glocation}") ) {
              [System.String]$location_disp  = $Location_Dict["${glocation}"]
            }
            Write-Output "The ${groupname} resource group will be used. Its location is ${location_disp}."
            "${Env:GITHUB_ENV}" -eq $null;
            if ( "${Env:GITHUB_ENV}" -eq $null ) {
              "GROUP_NAME=${groupname}" >> "${Env:GITHUB_ENV}"
              Get-Content -LiteralPath "${Env:GITHUB_ENV}"
            }
          } else {
            Write-Error -Message 'There is no resource group found. '
            exit 1;
          }
          
          [System.String]$LocationUsed = "${Env:LOCATION}"
          if ( "${LocationUsed}" -eq 'default' ) {
            [System.String]$LocationUsed = "${glocation}"
          }
          [System.String]$LocationUsed_Disp  = "${LocationUsed}";
          if ( $Location_Dict.Contains("${LocationUsed}") ) {
            [System.String]$LocationUsed_Disp  = $Location_Dict["${LocationUsed}"]
          }
          Write-Output "The location ${LocationUsed_Disp} will be used."
      
      - name: Test
        working-directory: ./Azure/Lab/
        env:
          LOCATION     : "${{ github.event.inputs.location }}"
          VM_USERNAME  : "${{ secrets.USERNAME_DEFAULT }}"
          VM_PASSWORD  : "${{ secrets.PASSWORD_DEFAULT }}"
        run: |
          ${Env:PASSWORD_DEFAULT}
          [System.String]                             $username   =  "${Env:VM_USERNAME}";
          [System.Security.SecureString]              $password   = ("${Env:VM_PASSWORD}" | ConvertTo-SecureString -AsPlainText -Force);
          [System.Management.Automation.PSCredential] $credential = [System.Management.Automation.PSCredential]::New(${username},${password});
          ${credential}.Username

