
name: Azure Lab
run-name: Lab Practice

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: Access Token
        required: true
      account_id:
        type: string
        description: Account ID
        required: true

jobs:

  Create-an-Azure-Resource-using-scripts:
    runs-on: windows-2022
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Prepare
        shell: powershell
        run: |
          [System.String[]]$packages = @(
            ##'Az.Accounts',
            'Az.Resources',
            'Az'
          );
          [System.String[]]$skip = @(
            'Az'
          );
          ## https://www.powershellgallery.com/packages/Az/
          foreach ($azp in $packages)
          {
            if ( ${skip}.Contains("${azp}") ) {
              continue;
            }
            Install-Module -Name "${azp}" -Scope CurrentUser -Repository PSGallery -AllowClobber -Force;
          }
          foreach ($azp in $packages)
          {
            if ( ${skip}.Contains("${azp}") ) {
              continue;
            }
            Get-InstalledModule -Name "${azp}";
          }
          

      - name: Connect
        env:
          TOKEN : "${{ github.event.inputs.token }}"
          ID    : "${{ github.event.inputs.account_id }}"
        shell: powershell
        run: |
          [System.String]$Token = "${Env:TOKEN}";
          [System.String]$Id    = "${Env:ID}";
          [Microsoft.Azure.Commands.Profile.Models.Core.PSAzureProfile]$Profile=(Connect-AzAccount -AccessToken "${Token}" -AccountId "${Id}");
          ${Profile};
          [System.String]$Expire = (Get-AzAccessToken).ExpiresOn.ToString('u');
          "The session will expire at ${Expire}."
          Get-AzSubscription;

          [Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceGroup[]]$ResourceGroups = (Get-AzResourceGroup);
          ${ResourceGroups}
          "GROUP_NAME=${ResourceGroups}.ResourceGroupName" >> "${GITHUB_ENV}"
          Get-Content -LiteralPath "${GITHUB_ENV}"
      
      - name: Test
        working-directory: ./Azure/Lab/
        run: |
          $username = 'Username';
          $password = 'Password' | ConvertTo-SecureString -AsPlainText -Force;
          $credential = [PSCredential]::New($username,$password);
          ${credential}.GetType().FullName;
          ${password}.GetType().FullName;

