
name: Data
run-name: Data Wokers

on:
  
  # Daily
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '33 22 *  *  *'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Data/**.*'

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04

jobs:
  
  Job-XHS:
    
    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    environment: Data
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Check Environment
        working-directory: Data/
        run: |
          bash Bash/Test.sh

      - name: Download Data
        env:
          UserAgent  : "${{ secrets.UserAgent }}"
          URL_Base   : "${{ secrets.XHS_URL_Base }}"
          VAR_Target : "${{ secrets.XHS_VAR_Target }}"
        working-directory: Data/
        run: |
          bash Bash/XHS.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: X_Data
          path: Data/Output/
