name: Dispatch DEMO
run-name: Dispatch DEMO

on:

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04
      number-base:
        description: 'Base Number'
        required: true
        type: number
        default: 101015000


jobs:

  job-cms-seed:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    outputs:
      segments: ${{ steps.seek.outputs.segments }}
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Seeds Generation
        id: seek
        env:
          ID_Base  : "${{ inputs.number-base }}"
        working-directory: Dispatch/
        run: |
          idstart="${ID_Base::-5}00000"
          segments=$(
            for seg in {0..5}
              do
                segment="${seg}000"
                echo $((idstart + segment))
              done |
              jq --raw-input |
              jq --compact-output --slurp '.'
          )
          if [[ -n "${GITHUB_OUTPUT}" ]]
          then
            echo "segments=${segments}"
            echo "segments=${segments}" >> "${GITHUB_OUTPUT}"
          fi

  job-matrex:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    environment: CMS-DEMO
    needs:
      - job-cms-seed
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Segment Job
        env:
          URL_Prefix : "${{ secrets.PREFIX }}"
          SEGMENT    : "${{ matrix.segment }}"
        working-directory: Dispatch/
        run: |
          echo "${SEGMENT}"
