name: Dispatch DEMO
run-name: Dispatch DEMO

on:

  workflow_dispatch:
    inputs:
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      system-linux:
        description: 'Linux Version'
        required: true
        default: 'ubuntu-24.04'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04
      number-base:
        description: 'Base Number'
        required: true
        type: number
        default: 101000000
      thousands:
        description: 'Thousands'
        required: true
        type: number
        default: 3

jobs:

  job-cms-seed:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    outputs:
      segments: ${{ steps.seek.outputs.segments }}
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Seeds Generation
        id: seek
        env:
          Thousands : '${{ inputs.thousands }}'
        working-directory: Dispatch/
        shell: bash
        run: |
          segments=$(
            for seg in $(seq 0 $((Thousands-1)))
              do
                echo "${seg}"
              done |
              jq --compact-output --slurp '.'
          )
          if [[ -n "${GITHUB_OUTPUT}" ]]
          then
            echo "segments=${segments}" |
              tee --append "${GITHUB_OUTPUT}"
          fi

  job-matrex:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    environment: CMS-DEMO
    needs:
      - job-cms-seed
    strategy:
      matrix:
        segment: ${{ fromJSON(needs.job-cms-seed.outputs.segments) }}
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - name: Segment Job
        env:
          Prefix  : '${{ secrets.PREFIX }}'
          Number  : '${{ inputs.number-base }}'
          Segment : '${{ matrix.segment }}'
        working-directory: Dispatch/
        shell: bash
        run: |
          bash search.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: '${{ env.sname }}'
          path: Dispatch/segment/

  job-combine:

    runs-on: ${{ inputs.system-linux || 'ubuntu-latest' }}
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      ## https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    needs:
      - job-matrex
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
          ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
        with:
          path: Dispatch/segment/
          pattern: 'segment-*'
          merge-multiple: true

      - name: Combine
        working-directory: Dispatch/
        shell: bash
        run: |
          bash combine.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: 'combine-${{ inputs.number-base }}'
          path: Dispatch/combine/

      - name: Clean Up
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: Dispatch/
        shell: bash
        run: |
          curl --location \
            --header 'Accept: application/vnd.github+json' \
            --header "Authorization: Bearer ${GITHUB_TOKEN}" \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" |
            jq '[.artifacts[] | [.name,.id]]' |
            jq --raw-output '.[] | @tsv' |
            sed --silent 's/^segment-[0-9]*\t//p' |
            while read -r artifact_id
            do
              curl --location \
                --request DELETE \
                --header 'Accept: application/vnd.github+json' \
                --header "Authorization: Bearer ${GITHUB_TOKEN}" \
                --header 'X-GitHub-Api-Version: 2022-11-28' \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/artifacts/${artifact_id}"
            done



