
name: Font (Windows)
run-name: Fonts (Windows)

on:

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Font/**.*'

  workflow_dispatch:

jobs:

  Scan-Font:
    runs-on: windows-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    defaults:
      run:
        shell: powershell

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Scan Existing Fonts
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\ScanFont.ps1;

      - uses: actions/upload-artifact@v4
        # https://github.com/actions/upload-artifact
        with:
          name: Fonts
          path: Font\File\Basic\

      - name: Test
        shell: powershell
        run: |
          'Get-WindowsCapability -Online';
          Get-WindowsCapability -Online;
          'Get-WindowsOptionalFeature -Online'
          Get-WindowsOptionalFeature -Online;
