
name: Font

on:
  workflow_dispatch:

jobs:

  Scan-Font:
    runs-on: windows-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    defaults:
      run:
        shell: powershell

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Scan
        shell: powershell
        run: |
          Add-Type -AssemblyName PresentationFramework;
          Get-ChildItem -LiteralPath 'C:\Windows\Fonts' |
            ForEach-Object -Process {
              [System.String]$FullName = $_.FullName;
              try { 
                [System.Windows.Media.GlyphTypeface]$FontFile = New-Object -TypeName System.Windows.Media.GlyphTypeface -ArgumentList "${FullName}";
                $FontFile;
              } catch {
                ##Write-Error -Message 
                "Ignoring ${FullName}";
              };
            }
