
name: Font (Windows)
run-name: Fonts (Windows)

on:

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'Font/**.*'

  workflow_dispatch:

jobs:

  Basic-Font:
    runs-on: windows-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    defaults:
      run:
        shell: powershell

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Scan Existing Fonts
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\ScanFontBasic.ps1;

      - uses: actions/upload-artifact@v4
        # https://github.com/actions/upload-artifact
        with:
          name: Fonts
          path: Font\File\Basic\

      - name: List Optional Features
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\ListOptionalFeature.ps1
          .\Script\PowerShell\ListLanguageFont.ps1

  Optional-Font:
    strategy:
      matrix:
        lang: 
          - Hant
          - Hans
          - Jpan
          - Kore
    runs-on: windows-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    needs: Basic-Font
    defaults:
      run:
        shell: powershell
    env:
      Language: ${{ matrix.lang }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Install Font
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\InstallOptional.ps1

      - name: List Optional Features
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\ListOptionalFeature.ps1
          .\Script\PowerShell\ListLanguageFont.ps1

      - uses: actions/download-artifact@v4
        ## https://github.com/actions/download-artifact
        with:
          name: Fonts
          path: Font\File\Basic\

      - name: Optional Font
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\ScanFontOptional.ps1 -InformationAction Continue;
          if ( "${env:GITHUB_ENV}" -ne $null ) {
            "ARTIFACT_TARGET=Optional$env:Language";
            "ARTIFACT_TARGET=Optional$env:Language" >> "${env:GITHUB_ENV}";
          }

      - uses: actions/upload-artifact@v4
        ## https://github.com/actions/upload-artifact
        with:
          name: ${{ env.ARTIFACT_TARGET }}
          path: Font\File\Optional\

  CJK-Font:
    strategy:
      matrix:
        lang: 
          - zh-TW
          - zh-HK
          - zh-SG
          - zh-CN
          - ja-JP
          - ko-KR
    runs-on: windows-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    needs: Optional-Font
    defaults:
      run:
        shell: powershell
    env:
      Language: ${{ matrix.lang }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
        ## https://github.com/actions/download-artifact
        with:
          path: Font\File\CJK\

      - name: Get Font
        working-directory: Font\
        shell: powershell
        run: |
          .\Script\PowerShell\GetFontLanguage.ps1
          if ( "${env:GITHUB_ENV}" -ne $null ) {
            "ARTIFACT_TARGET=font-$env:Language";
            "ARTIFACT_TARGET=font-$env:Language" >> "${env:GITHUB_ENV}";
          }

      - uses: actions/upload-artifact@v4
        ## https://github.com/actions/upload-artifact
        with:
          name: ${{ env.ARTIFACT_TARGET }}
          path: Font\File\Target\
