
name: MongoDB
run-name: MongoDB

on:

  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '5  4  *  *  WED'
          #   │  │  │  │  │
          #   │  │  │  │  └─── day of the week  (0–6, SUN-SAT)
          #   │  │  │  └────── month            (1–12)
          #   │  │  └───────── day of the month (1–31)
          #   │  └──────────── hour             (0–23)
          #   └─────────────── minute           (0–59)

  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
    branches:
      - 'main'
    paths:
      - 'MongoDB/**.*'

  workflow_dispatch:

jobs:

  Get-Data-Catalog:
    name: Get Data Catalog
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    environment: MongoDB2
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - name: Test
        working-directory: MongoDB/
        run: |
          bash Script/Bash/Test.sh

      - name: Get Data Catalog
        env:
          ENDPOINT : "${{ secrets.HTTPS_ENDPOINT }}"
          API_KEY  : "${{ secrets.APP_API_KEY }}"
        working-directory: MongoDB/
        run: |
          mkdir --parent Artifact/
          bash Script/Bash/Get-Data-Catalog.sh |
            tee Artifact/Data-Catalog.json

      - uses: actions/upload-artifact@v4
          ## https://github.com/actions/upload-artifact
        with:
          name: Data-Catalog
          path: MongoDB/Artifact/Data-Catalog.json

  Count-Documents:
    name: Count Documents
    needs: Get-Data-Catalog
    runs-on: ubuntu-latest
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    environment: MongoDB1
    defaults:
      run:
        shell: bash
          ## https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
          ## https://github.com/actions/download-artifact
        with:
          name: Data-Catalog
          path: MongoDB/

      - name: Test
        env:
          ENDPOINT : "${{ secrets.DATA_API_URL_ENDPOINT }}"
          API_KEY  : "${{ secrets.DATA_API_KEY }}"
          CLUSTER  : "${{ secrets.CLUSTER_VENDOR_LOCATION }}"
        working-directory: MongoDB/
        run: |
          ls -R
          bash Script/Bash/TestAPI.sh
