
name: Test
run-name: Test Artifact

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: 'Access Token'
        required: true
      account_id:
        type: string
        description: 'Account ID'
        required: true

jobs:

  Testing:
    runs-on: windows-2022
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    environment: AzureLab
    defaults:
      run:
        shell: pwsh

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout
      
      - name: Generate Files
        env:
          TOKEN : "${{ github.event.inputs.token }}"
          ID    : "${{ github.event.inputs.account_id }}"
          GUARD : "${{ secrets.PRIVACY_GUARD }}"
        working-directory: Artifact\
        run: |
          "
          ACCESS_TOKEN='${Env:TOKEN}'
          ACCOUNT_ID='${Env:ID}'
          " | openssl enc -aes256 -pbkdf2 -e -pass pass:"${Env:GUARD}" > es256.encrypted

      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: Artifact\es256.encrypted
