
name: Test
run-name: Test Artifact

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: 'Access Token'
        required: true
      account_id:
        type: string
        description: 'Account ID'
        required: true

jobs:

  Testing:
    runs-on: windows-2022
      ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    environment: AzureLab
    defaults:
      run:
        shell: pwsh

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        ## https://github.com/actions/checkout

      - uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: Artifact/
          